FROM python:3.10-slim-buster

COPY th3-v2/*.py th3/
COPY th3-v2/requirements.txt th3/

WORKDIR /th3
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

CMD ["python3", "th3-server.py"]